### ISSUE TITLE
As a cg customer, I would like a link to the buildpack release notes in the notification email

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-buildpack-notify#29]
In order to raise awareness of changes in new buildpack releases and prevent issues that could arise from a restage (ie a runtime version is no longer supported), I would like to have the notifier include a link to the release notes of the new buildpack version.

## Acceptance Criteria

* [x] buildpack notification emails contain a link to the updated version release notes

--- 

## Security considerations

None

**Comment by ccostino** [comment]
If there's a way to know which buildpacks were modified with the release, I hope to be able to include the links to the specific ones.

I'm assuming the links should point to the releases page in GitHub for these?  e.g., https://github.com/cloudfoundry/python-buildpack/releases for Python?

**Comment by ccostino** [comment]
It looks like I should be able to see the specific version of what was updated, and therefore go to the specific release for a given update, e.g., https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.45 instead of the main releases page at https://github.com/cloudfoundry/python-buildpack/releases.

I've asked folks in a [previous Slack thread](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1630612758034000?thread_ts=1626809452.018300&cid=C09CR1Q9Z) what they'd prefer to get a sense of what's best for these changes.

**Comment by neilmb** [comment]
As a user of the python buildpack who gets these notifications, I would like the link in a notification email to point to https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.45 where 1.7.45 is the **new** version of the buildpack so that I can see what versions of the packaged software I will be upgrading to.

**Comment by ccostino** [comment]
Thanks, @neilmb!

**Comment by ccostino** [comment]
PR now available: https://github.com/cloud-gov/cg-buildpack-notify/pull/31

**Comment by ccostino** [comment]
This has now been merged - I think we just missed the last round of notifications, but this should be working for the next one.
